server:
  port: 8080
  servlet:
    context-path: /admin/
spring:
  application:
    name: mountain-admin
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mountain_admin_auth?useUnicode=true&characterEncodeing=utf8&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000 #连接超时 毫秒
auth:
  tokenValiditySeconds: 1200  #token存储到redis的过期时间
  clientId: mountain
  clientSecret: mountain
  cookieDomain: localhost
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/mountain.keystore
    secret: mountain
    alias: mountainkey
    password: mountain